# SPDX-FileCopyrightText: 2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
    - name: Install Nix
      uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6
      with:
        extra-conf: |
          experimental-features = nix-command flakes
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c
    - name: Docker
      uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7
      with:
        registry: ghcr.io
        password: ${{ secrets.GITHUB_TOKEN }}
        username: ${{ github.repository_owner }}
    - name: GoReleaser
      run: |
        nix develop ./nix --command \
        # Goreleaser doesn't really interact well with "~" or environment
        # variables.
        mkdir -p ~/.ssh
        ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
        goreleaser release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_CASK_TOKEN: ${{ secrets.HOMEBREW_CASK_TOKEN }}
        NUR_TOKEN: ${{ secrets.NUR_TOKEN }}
        SCOOP_TOKEN: ${{ secrets.SCOOP_TOKEN }}
        WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}
