# SPDX-FileCopyrightText: 2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Review

on:
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
    - name: Install Nix
      uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6
      with:
        extra-conf: |
          experimental-features = nix-command flakes
    - name: Cocogitto Check
      run: |
        nix develop ./nix --command \
        cog check --from-latest-tag
    - name: GoReleaser Check
      run: |
        nix develop ./nix --command \
        goreleaser check
    - name: REUSE Check
      run: |
        nix develop ./nix --command \
        reuse lint
  test:
    needs: check
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check Out Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Set Up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
      with:
        cache: true
        go-version: 1.26.5
    - name: Test
      run: go test work -coverprofile=coverage.txt -covermode=atomic
    - name: Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
      with:
        files: ./coverage.txt
